### ISSUE TITLE
Is CosToM need an input of object mass when I simulate a pick-and-place action?

### ISSUE THREAD

**Issue by zxie8** [anmuller/CusToM#5]
I'm now trying to use CosToM to calculate the external forces (similar to the Muller's paper 'Motion-based prediction of hands and feet contact efforts during asymmetric handling tasks'. The original idea is that by calculating the external force on hand, I can estimate the mass of the object. But I'm kind of confused that do you need an input of the mass of the object to do the simulation?

**Comment by cpontonn** [comment]
Dear CBPPGZ, force prediction is globally an indeterminate problem that needs assumption to work. in the paper, we assumed that forces at the interface between the subject and the load were able to achieve both dynamical equilibrium (load and subject), therefore we needed some rough values of the Inertial parameters of the load to make it usable.It was necessary especially due to the fact that the load was hold with two hands. In your case, if your subject is only holding a mass with a single hand, you cantry adding simple contact points on the hand and run the simulation.
